output = "../internal/models"
wipe = "true"
no-hooks = "true"
no-auto-timestamps = "true"
no-rows-affected = "true"
no-tests = "true"
tag-ignore = ["todo.app_user_id"]
add-enum-types = true

[psql]
  dbname = "gotodo"
  host = "host.docker.internal"
  port = 5432
  user = "gotodo"
  pass = "gotodo"
  sslmode = "disable"
  blacklist = ["goose_db_version", "sessions"]
