services:
  db:
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    restart: "no"
    environment:
      POSTGRES_DB: gotodo
      POSTGRES_USER: gotodo
      POSTGRES_PASSWORD: gotodo

  inbucket:
    image: inbucket/inbucket:latest
    ports:
      - "2500:2500"
      - "9000:9000"

volumes:
  pgdata:
