# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task --list-all

  lint:
    cmds:
      - docker run --rm -v {{toSlash .ROOT_DIR}}:/app -w /app golangci/golangci-lint:v2.6.2 golangci-lint run -v --timeout 5m

  upgrade-libraries:
    cmds:
      - go get go@latest
      - go get -u ./...
      - go fmt ./...
      - go mod tidy
      - go mod verify

  tidy:
    cmds:
      - go fmt ./...
      - go mod tidy -v

  audit:
    cmds:
      - go vet ./...
      - go run honnef.co/go/tools/cmd/staticcheck@latest -checks=all,-ST1000,-U1000 ./...
      - go mod verify

  build:
    cmds:
      - go build -ldflags='-s' -o=./bin/web{{exeExt}} ./cmd/web

  run:
    deps: [build]
    cmds:
      - ./bin/web{{exeExt}}

  build-goose:
    cmds:
      - go build -o ./migrate{{exeExt}} gotodo.rasc.ch/cmd/migrate
    sources:
      - ./cmd/migrate/*.go
      - ./migrations/*.sql
    generates:
      - ./migrate{{exeExt}}

  db-migration-new:
    deps: [build-goose]
    cmds:
      - ./migrate{{exeExt}} create {{.CLI_ARGS}} sql

  db-migration-new-go:
    deps: [build-goose]
    cmds:
      - ./migrate{{exeExt}} create {{.CLI_ARGS}} go

  db-migration-up:
    deps: [build-goose]
    cmds:
      - ./migrate{{exeExt}} up

  db-migration-reset:
    deps: [build-goose]
    cmds:
      - ./migrate{{exeExt}} reset

  db-migration-status:
    deps: [build-goose]
    cmds:
      - ./migrate{{exeExt}} status

  db-codegen:
    cmds:
      - docker build -t sqlboilercodegen -f sqlboiler/Dockerfile .
      - docker run -v {{toSlash .ROOT_DIR}}:/src sqlboilercodegen
      - go run gotodo.rasc.ch/cmd/tsgen


